variables:
  system.debug: true
  env: dev
  rg: tp2022-$(env)-global-rg
  instLocationB: "westeurope, eastus2, northeurope"
  instName: "euw,use2,eun"
  instNameB: "euw, use2, eun"

parameters:
- name: build_ci
  type: string
  default: janono.demo.tp2022-ci

trigger:
- none

resources:
  pipelines:
  - pipeline: janono.demo.tp2022-ci
    source: janono.demo.tp2022-ci
    trigger:
      branches:
      - release/*
      - master
      - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: provisioning
  jobs:
  - job: provisioning_job
    steps:
    - download: ${{ parameters.build_ci }}
    - task: AzureResourceGroupDeployment@2
      displayName: Azure Deployment:Create Or Update Resource Group action on $(rg)
      inputs:
        azureSubscription: AzureServiceConnection
        resourceGroupName: $(rg)
        location: West Europe
        csmFile: $(Pipeline.Workspace)/${{ parameters.build_ci }}/drop arm/azuredeploy.json
        csmParametersFile: $(Pipeline.Workspace)/${{ parameters.build_ci }}/drop arm/azuredeploy.parameters.json
        overrideParameters: -instLocation [$(instLocationB)] -instName [$(instNameB)] -environmentType $(env)
    - task: AzurePowerShell@5
      displayName: 'Azure PowerShell script: InlineScript'
      inputs:
        azureSubscription: AzureServiceConnection
        ScriptType: InlineScript
        Inline: |
          Write-Host $(rg)
          $resourceGroupName = "$(rg)"
          $webSites=Get-AzWebApp -ResourceGroupName $resourceGroupName
          $TmProfile = get-AzTrafficManagerProfile -ResourceGroupName $resourceGroupName
          foreach($web in $webSites)
          {
              if($TmProfile.Endpoints.Count -eq 0)
              {
                  Write-Output "Adding 1 endpoint"
                  Add-AzTrafficManagerEndpointConfig -EndpointName $web.Name -TrafficManagerProfile $TmProfile -Type AzureEndpoints -Target $web.HostNames[0] -EndpointLocation $web.Location -EndpointStatus Enabled -TargetResourceId $web.Id
              }
              else
              {
                  if(($TmProfile.Endpoints -ne $null) -and ($TmProfile.Endpoints.Name.Contains($web.Name) -eq $false))
                  {
                      Write-Output "Adding next endpoint"
                      Add-AzTrafficManagerEndpointConfig -EndpointName $web.Name -TrafficManagerProfile $TmProfile -Type AzureEndpoints -Target $web.HostNames[0] -EndpointLocation $web.Location -EndpointStatus Enabled -TargetResourceId $web.Id
                  }
              }
          }
          Set-AzTrafficManagerProfile -TrafficManagerProfile $TmProfile
        azurePowerShellVersion: LatestVersion
        pwsh: true

- stage: AppDeploy
  jobs:
  - job: AppDeploy_job
    steps:
    - task: AzureFunctionApp@1
      displayName: 'Azure Function App Deploy: mimuw-$(env)-$(instName)site'
      inputs:
        azureSubscription: AzureServiceConnection
        appType: functionApp
        appName: mimuw-$(env)-$(instName)site
        package: $(Pipeline.Workspace)/${{ parameters.build_ci }}/drop/*.zip

- stage: Deprovision
  jobs:
  - job: Deprovision_job
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: Azure Deployment:DeleteRG action on $(rg)
      inputs:
        azureSubscription: AzureServiceConnection
        action: DeleteRG
        resourceGroupName: $(rg)
