pool:
  name: Azure Pipelines
variables:
  buildConfiguration: Release
  system.debug: true


pr:
  branches:
    include:
    - master
    - release/*
    - develop
  paths:
    exclude:
    - .azuredevops

steps:
- task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.x

- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute

- script: |
    pip install pre-commit
    pre-commit --version
    pre-commit run --all-files
  condition: succeededOrFailed()
  displayName: Execture pre-commit

- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    projects: '**/*.csproj'
    arguments: --output publish_output --configuration $(buildConfiguration)

- task: ArchiveFiles@2
  displayName: Archive files
  inputs:
    rootFolderOrFile: publish_output/
    includeRootFolder: false

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code coverage"
    workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  displayName: Publish Test Results **/*.trx
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    searchFolder: '$(Agent.TempDirectory) '
    mergeTestResults: true
    failTaskOnFailedTests: true
    buildConfiguration: $(buildConfiguration)
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop arm'
  inputs:
    PathtoPublish: src/MIMUW.ResourceGroup
    ArtifactName: drop arm
